---
title: "Reproducible document"
author: "Mikkel Breinholt Kjær"
format: html
---

```{r Setup}
#| message: false
#| warning: false

library(tidyverse)
library(NHANES)
nhanes_small <- read_csv(here::here("data/nhanes_small_test.csv"))
```

```{r}
nhanes_small
```

## Table of results
### Smaller?
#### Definetively smaller

```{r mean-age-bmi-table}
nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "Mean vaules of age and BMI by education- an diabetes status")
```


## Prettier table
```{r prettier-table}
#| echo: false


nhanes_small %>%
  filter(!is.na(diabetes), !is.na(education)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = TRUE),
    mean_bmi = mean(bmi, na.rm = TRUE)
  ) %>%
  ungroup() %>% 
    mutate(
        mean_age = round(mean_age, digits = 1),
        mean_bmi = round(mean_bmi, digits = 1),
        education = str_to_sentence(education)
    ) %>% 
    rename(
        "Diabetes Status" = diabetes,
        "Mean Age" = mean_age,
        "Mean BMI" = mean_bmi,
        "Education" = education
    ) %>% 
    
    
  knitr::kable(caption = "Mean vaules of age and BMI by education- and diabetes status")

```

